"""PrototypeActivationService — commit, rollback, wiring, and runtime status.

Extracted from PrototypeGenerationService (P2-1) to isolate the transactional
lifecycle of a generated prototype: staging promotion, main-script wiring,
index writeback, rollback on failure, and runtime readiness queries.
"""

from __future__ import annotations

import logging
import shutil
from datetime import datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

from renpy_mcp.services.script_render_service import (
    final_path_from_staging,
    staging_path_from_final,
)

if TYPE_CHECKING:
    from renpy_mcp.blueprint.models import ChapterSummary
    from renpy_mcp.services.project_manager import ProjectManager
    from renpy_mcp.services.prototype_generation_service import PrototypeScene

logger = logging.getLogger(__name__)


class PrototypeActivationService:
    """Manage the transactional lifecycle of a generated prototype.

    Responsibilities:
    - Main script wiring (managed region in game/script.rpy)
    - Backup / restore of game/script.rpy
    - Commit: promote staging → final, clean up old artifacts
    - Rollback: revert staging files, index entries, and assets
    - Index writeback (scene metadata to meta/index.json)
    - Prototype manifest management
    - Runtime readiness queries
    """

    _MANAGED_START = "    # PROTOTYPE START (managed)"
    _MANAGED_END = "    # PROTOTYPE END (managed)"
    _DEFAULT_TEMPLATE_MARKERS = (
        "Welcome to your new Ren'Py project!",
        "Hello from the Ren'Py MCP server!",
        "Generated by the Ren'Py MCP server.",
    )

    def __init__(self, pm: "ProjectManager | None") -> None:
        self.pm = pm

    # ------------------------------------------------------------------
    # Main script wiring
    # ------------------------------------------------------------------

    def wire_main_script_to_prototype(self, project_name: str, entry_label: str) -> None:
        """Update game/script.rpy to call the prototype entry label.

        Behavior:
            - If the file already contains a managed region, only the call
              statement inside that region is updated.
            - If the file is empty or contains default template content,
              it is replaced with a managed region.
            - Otherwise, a RuntimeError is raised to avoid overwriting
              user-customised script logic.
        """
        if self.pm is None:
            raise RuntimeError("ProjectManager is required for script wiring")

        project_dir = self.pm._project_dir(project_name)
        script_path = project_dir / "game" / "script.rpy"
        script_path.parent.mkdir(parents=True, exist_ok=True)

        managed_start = self._MANAGED_START
        managed_end = self._MANAGED_END

        existing = script_path.read_text(encoding="utf-8") if script_path.exists() else ""

        # Case 1: Already has managed region → update only the region
        if managed_start in existing and managed_end in existing:
            lines = existing.splitlines()
            new_lines: list[str] = []
            skipping = False
            for line in lines:
                if line == managed_start:
                    skipping = True
                    new_lines.append(managed_start)
                    new_lines.append(f"    call {entry_label}")
                    new_lines.append("    return")
                    continue
                if line == managed_end:
                    skipping = False
                    new_lines.append(managed_end)
                    continue
                if not skipping:
                    new_lines.append(line)
            script_path.write_text("\n".join(new_lines) + "\n", encoding="utf-8")
            return

        # Case 2: Default template or empty → safe to replace
        is_default = any(marker in existing for marker in self._DEFAULT_TEMPLATE_MARKERS)
        if not existing.strip() or is_default:
            script_path.write_text(
                f"label start:\n{managed_start}\n    call {entry_label}\n    return\n{managed_end}\n",
                encoding="utf-8",
            )
            return

        # Case 3: Non-template content without managed region → fail explicitly
        raise RuntimeError(
            f"Cannot safely wire prototype to {script_path}: file contains unrecognized content. "
            "Either start from a default template or add a managed region."
        )

    # ------------------------------------------------------------------
    # Main script backup / restore
    # ------------------------------------------------------------------

    def backup_main_script(self, project_name: str) -> str | None:
        """Return the current content of game/script.rpy for potential rollback."""
        if self.pm is None:
            return None
        project_dir = self.pm._project_dir(project_name)
        script_path = project_dir / "game" / "script.rpy"
        if script_path.exists():
            return script_path.read_text(encoding="utf-8")
        return None

    def restore_main_script(self, project_name: str, content: str | None) -> None:
        """Restore game/script.rpy to a previously backed-up content."""
        if self.pm is None or content is None:
            return
        project_dir = self.pm._project_dir(project_name)
        script_path = project_dir / "game" / "script.rpy"
        try:
            script_path.write_text(content, encoding="utf-8")
        except OSError:
            logger.warning("Failed to restore script.rpy for project %s", project_name, exc_info=True)

    # ------------------------------------------------------------------
    # Staged replace: commit
    # ------------------------------------------------------------------

    def commit_prototype_replacement(
        self,
        project_name: str,
        new_scene_ids: list[str],
        staging_script_path: str,
        round_id: str | None = None,
    ) -> None:
        """Finalize prototype replacement by promoting the staging script and removing old artifacts.

        This must only be called after all new prototype steps
        (write_script, wire_main_script, update_index) have succeeded.
        """
        if self.pm is None:
            return

        project_dir = self.pm._project_dir(project_name)
        final_script_path = final_path_from_staging(staging_script_path)
        staging_file = project_dir / staging_script_path
        final_file = project_dir / final_script_path

        # 1. Promote staging file to final path (fail-fast, atomic-ish replace)
        if staging_file.exists():
            staging_file.replace(final_file)

        # 2. Promote round-scoped staging assets to final paths
        if round_id:
            staging_dir = project_dir / "game" / "__staging__" / round_id
            if staging_dir.exists():
                for src in staging_dir.rglob("*"):
                    if src.is_file() and "__backup__" not in str(src):
                        rel = src.relative_to(staging_dir)
                        dst = project_dir / "game" / rel
                        dst.parent.mkdir(parents=True, exist_ok=True)
                        src.replace(dst)
                try:
                    shutil.rmtree(staging_dir)
                except OSError:
                    logger.warning("Failed to remove staging dir: %s", staging_dir)

        # 3. Remove old prototype index entries (keep only new_scene_ids)
        index = self.pm.read_project_index(project_name)
        if index and "scenes" in index:
            old_ids = [
                sid for sid, s in index["scenes"].items()
                if isinstance(s, dict) and s.get("source") == "prototype" and sid not in new_scene_ids
            ]
            if old_ids:
                for sid in old_ids:
                    del index["scenes"][sid]
                self.pm.write_project_index(project_name, index)

        # 4. Remove old prototype files (keep only the new final file)
        game_dir = project_dir / "game"
        if game_dir.exists():
            new_file_name = Path(final_script_path).name
            for proto_file in game_dir.glob("prototype_*.rpy"):
                if proto_file.name != new_file_name:
                    try:
                        proto_file.unlink()
                    except OSError:
                        logger.warning("Failed to remove old prototype file: %s", proto_file, exc_info=True)
            for leftover in game_dir.glob("prototype_*.__staging__.rpy"):
                try:
                    leftover.unlink()
                except OSError:
                    logger.warning("Failed to remove leftover staging file: %s", leftover, exc_info=True)

    # ------------------------------------------------------------------
    # Staged replace: rollback
    # ------------------------------------------------------------------

    def rollback_prototype_generation(
        self,
        project_name: str,
        staging_script_path: str | None,
        new_scene_ids: list[str],
        old_script_content: str | None,
        generated_asset_paths: list[str] | None = None,
        round_id: str | None = None,
    ) -> None:
        """Rollback a failed prototype generation round.

        Restores the main script, removes the staging prototype file,
        removes newly written index entries, and deletes any visual assets
        that were generated during this round.
        """
        if self.pm is None:
            return

        # 1. Restore main script.rpy
        self.restore_main_script(project_name, old_script_content)

        # 2. Remove staging file only — never touch the stable final file
        if staging_script_path:
            project_dir = self.pm._project_dir(project_name)
            staging_file = project_dir / staging_script_path
            try:
                if staging_file.exists():
                    staging_file.unlink()
            except OSError:
                logger.warning("Failed to remove staging file: %s", staging_file, exc_info=True)

        # 3. Remove newly written index entries
        index = self.pm.read_project_index(project_name)
        if index and "scenes" in index:
            changed = False
            for sid in new_scene_ids:
                if sid in index["scenes"]:
                    del index["scenes"][sid]
                    changed = True
            if changed:
                self.pm.write_project_index(project_name, index)

        # 4. Remove round-scoped staging directory
        if round_id:
            project_dir = self.pm._project_dir(project_name)
            staging_dir = project_dir / "game" / "__staging__" / round_id
            if staging_dir.exists():
                try:
                    shutil.rmtree(staging_dir)
                except OSError:
                    logger.warning("Failed to remove staging dir: %s", staging_dir, exc_info=True)

        # 5. Fallback: remove individual generated asset paths (legacy path)
        if generated_asset_paths:
            project_dir = self.pm._project_dir(project_name)
            for p in generated_asset_paths:
                abs_path = Path(p)
                if not abs_path.is_absolute():
                    abs_path = project_dir / p
                try:
                    if abs_path.exists() and abs_path.is_file():
                        abs_path.unlink()
                except OSError:
                    logger.warning("Failed to remove generated asset: %s", abs_path, exc_info=True)

    # ------------------------------------------------------------------
    # Index writeback
    # ------------------------------------------------------------------

    def update_index(
        self,
        project_name: str,
        chapter: "ChapterSummary",
        scenes: "list[PrototypeScene]",
        script_path: str,
        background_assets: dict[str, Any] | None = None,
        character_assets: dict[str, dict] | None = None,
        cjk_font_config: dict | None = None,
    ) -> None:
        """Update meta/index.json with full prototype scene metadata."""
        if self.pm is None:
            raise RuntimeError("ProjectManager is required for index writeback")

        index = self.pm.read_project_index(project_name) or {"scenes": {}}
        if "scenes" not in index:
            index["scenes"] = {}

        bg_assets = background_assets or {}
        char_assets = character_assets or {}
        project_dir = self.pm._project_dir(project_name)

        for i, scene in enumerate(scenes):
            bg_asset = bg_assets.get(scene.scene_id)
            bg_path_raw = bg_asset.get("path") if isinstance(bg_asset, dict) else bg_asset
            bg_check_raw = bg_asset.get("staging_path") if isinstance(bg_asset, dict) else None
            bg_placeholder = bg_asset.get("placeholder", True) if isinstance(bg_asset, dict) else True
            bg_path_str: str | None = None
            if isinstance(bg_path_raw, Path):
                if bg_path_raw.exists() or (
                    isinstance(bg_check_raw, str) and (project_dir / bg_check_raw).exists()
                ) or (
                    isinstance(bg_check_raw, Path) and bg_check_raw.exists()
                ):
                    bg_path_str = str(bg_path_raw.relative_to(project_dir).as_posix())
            elif isinstance(bg_path_raw, str):
                if (project_dir / bg_path_raw).exists() or (
                    isinstance(bg_check_raw, str) and (project_dir / bg_check_raw).exists()
                ) or (
                    isinstance(bg_check_raw, Path) and bg_check_raw.exists()
                ):
                    bg_path_str = bg_path_raw

            entry = {
                "chapter_id": chapter.id,
                "scene_id": scene.scene_id,
                "title": scene.title,
                "summary": scene.summary,
                "location": scene.location,
                "location_visual_brief": scene.location_visual_brief,
                "mood": scene.mood,
                "characters_present": scene.characters_present,
                "dialogue_beats": [b.model_dump() for b in scene.dialogue_beats],
                "sprite_plan": [sp.model_dump(exclude={"sprite_check_path"}) for sp in scene.sprite_plan],
                "next_scene_id": scene.next_scene_id,
                "label": scene.entry_label,
                "file_path": script_path,
                "source": "prototype",
                "order": i + 1,
                "background_asset_path": bg_path_str,
                "background_placeholder": bg_placeholder,
                "status": "generated",
            }
            index["scenes"][scene.scene_id] = entry

        # Persist character asset metadata at index top level
        if char_assets:
            def _char_asset_path(info: dict) -> str | None:
                p = info.get("path")
                check = info.get("staging_path") or p
                if isinstance(p, str):
                    if (project_dir / p).exists():
                        return p
                    if isinstance(check, str) and (project_dir / check).exists():
                        return p
                    if isinstance(check, Path) and check.exists():
                        return p
                    return None
                if isinstance(p, Path):
                    if p.exists():
                        return str(p.relative_to(project_dir).as_posix())
                    if isinstance(check, str) and (project_dir / check).exists():
                        return str(p.relative_to(project_dir).as_posix())
                    if isinstance(check, Path) and check.exists():
                        return str(p.relative_to(project_dir).as_posix())
                    return None
                return None

            index["character_assets"] = {
                name: {
                    "path": _char_asset_path(info),
                    "placeholder": info.get("placeholder", True),
                    "renderable": info.get("renderable", False),
                    "renderable_reason": info.get("renderable_reason", ""),
                }
                for name, info in char_assets.items()
            }

        if cjk_font_config:
            index["cjk_font_config"] = cjk_font_config

        self.pm.write_project_index(project_name, index)

    # ------------------------------------------------------------------
    # Managed entry label reader
    # ------------------------------------------------------------------

    def read_managed_entry_label(self, project_name: str) -> str | None:
        """Read the current wired entry label from game/script.rpy managed region."""
        if self.pm is None:
            return None
        project_dir = self.pm._project_dir(project_name)
        main_script = project_dir / "game" / "script.rpy"
        if not main_script.exists():
            return None

        text = main_script.read_text(encoding="utf-8")
        managed_start = self._MANAGED_START
        managed_end = self._MANAGED_END
        if managed_start not in text or managed_end not in text:
            return None

        lines = text.splitlines()
        in_region = False
        for line in lines:
            if line == managed_start:
                in_region = True
                continue
            if line == managed_end:
                in_region = False
                continue
            if in_region:
                stripped = line.strip()
                if stripped.startswith("call "):
                    parts = stripped[5:].split()
                    if parts:
                        return parts[0]
        return None

    # ------------------------------------------------------------------
    # Prototype runtime status
    # ------------------------------------------------------------------

    def get_prototype_runtime_status(self, project_name: str) -> dict:
        """Return the full prototype readiness status."""
        if self.pm is None:
            raise RuntimeError("ProjectManager is required for prototype runtime status")

        project_dir = self.pm._project_dir(project_name)

        manifest = self.pm.read_prototype_manifest(project_name)

        wired_entry_label = self.read_managed_entry_label(project_name)
        wired = wired_entry_label is not None

        entry_file_exists = False
        all_script_files_exist = False
        if manifest is not None:
            if manifest.entry_file:
                entry_file_exists = (project_dir / manifest.entry_file).exists()
            script_files = manifest.script_files or []
            all_script_files_exist = (
                all((project_dir / sf).exists() for sf in script_files)
                if script_files else False
            )

        has_valid_mode = (
            manifest is not None
            and manifest.mode in ("single_chapter", "multi_chapter")
        )

        entry_label_matches = (
            manifest is not None
            and manifest.entry_label is not None
            and wired_entry_label == manifest.entry_label
        )

        is_active = has_valid_mode and entry_label_matches and entry_file_exists

        manifest_consistent = (
            has_valid_mode and entry_label_matches and entry_file_exists and all_script_files_exist
        )

        is_buildable = is_active and manifest_consistent

        index = self.pm.read_project_index(project_name)
        proto_scenes = []
        if index and isinstance(index.get("scenes"), dict):
            proto_scenes = [
                s for s in index["scenes"].values()
                if isinstance(s, dict) and s.get("source") == "prototype"
            ]

        script_paths = {s.get("file_path") for s in proto_scenes if s.get("file_path")}
        script_exists = (
            all((project_dir / p).exists() for p in script_paths)
            if script_paths else False
        )

        manifest_dict = manifest.model_dump(mode="json") if manifest is not None else {}

        return {
            "has_prototype": len(proto_scenes) > 0,
            "scene_count": len(proto_scenes),
            "script_exists": script_exists,
            "wired": wired,
            "wired_entry_label": wired_entry_label,
            "entry_label_matches": entry_label_matches,
            "has_manifest": manifest is not None,
            "mode": manifest_dict.get("mode"),
            "entry_label": manifest_dict.get("entry_label"),
            "entry_file": manifest_dict.get("entry_file"),
            "script_files": manifest_dict.get("script_files", []),
            "chapter_ids": manifest_dict.get("chapter_ids", []),
            "is_active": is_active,
            "is_buildable": is_buildable,
            "manifest_consistent": manifest_consistent,
        }

    # ------------------------------------------------------------------
    # Prototype activation (multi-chapter and single-chapter)
    # ------------------------------------------------------------------

    def activate_multi_chapter_prototype(self, project_name: str) -> dict[str, Any]:
        """Activate a previously generated multi-chapter prototype as the runtime entry."""
        if self.pm is None:
            raise RuntimeError("ProjectManager is required for prototype activation")

        from renpy_mcp.blueprint.models import PrototypeManifest

        manifest = self.pm.read_prototype_manifest(project_name)
        if manifest is None:
            raise RuntimeError(
                f"Project {project_name!r} has no prototype_manifest.json. "
                "Run multi-chapter generate first."
            )

        entry_label = manifest.entry_label
        script_files = manifest.script_files
        if not entry_label or not script_files:
            raise RuntimeError("Manifest is incomplete: missing entry_label or script_files")

        project_dir = self.pm._project_dir(project_name)
        for sf in script_files:
            if not (project_dir / sf).exists():
                raise RuntimeError(f"Prototype script file missing: {sf}")

        old_script_content = self.backup_main_script(project_name)
        old_manifest = self.pm.read_prototype_manifest(project_name)

        try:
            self.wire_main_script_to_prototype(project_name, entry_label)
            manifest.mode = "multi_chapter"
            manifest.updated_at = datetime.utcnow().isoformat()
            self.pm.write_prototype_manifest(project_name, manifest)
        except Exception:
            logger.warning("Failed to activate multi-chapter prototype for %s", project_name, exc_info=True)
            self.restore_main_script(project_name, old_script_content)
            if old_manifest is not None:
                self.pm.write_prototype_manifest(project_name, old_manifest)
            raise

        return {
            "success": True,
            "mode": "multi_chapter",
            "entry_label": manifest.entry_label,
            "entry_file": manifest.entry_file,
            "script_files": manifest.script_files,
            "chapter_ids": manifest.chapter_ids,
        }

    def activate_single_chapter_prototype(
        self,
        project_name: str,
        entry_label: str,
        entry_file: str,
        chapter_ids: list[str],
        script_files: list[str],
    ) -> None:
        """Write the prototype manifest for an active single-chapter prototype."""
        if self.pm is None:
            return

        from renpy_mcp.blueprint.models import PrototypeManifest

        manifest = PrototypeManifest(
            mode="single_chapter",
            entry_label=entry_label,
            entry_file=entry_file,
            chapter_ids=chapter_ids,
            script_files=script_files,
            source="prototype",
            updated_at=datetime.utcnow().isoformat(),
        )
        self.pm.write_prototype_manifest(project_name, manifest)
